sudo: false
language: node_js
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get upgrade libstdc++6
node_js:
  - '6'
  - '5'
  - '4'
script:
  - npm run test:cover
after_success:
  - npm run coveralls
